# Generated by Django 4.2 on 2023-04-17 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=525)),
                ('manizl', models.CharField(max_length=525)),
                ('telefon', models.CharField(max_length=125)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.district')),
            ],
        ),
        migrations.CreateModel(
            name='WindEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('kuchlanish', models.FloatField()),
                ('tok_kuchi', models.FloatField()),
                ('harorat', models.FloatField()),
                ('quvvat', models.FloatField()),
                ('chastota', models.FloatField()),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='station.station')),
            ],
        ),
        migrations.CreateModel(
            name='WaterEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('kuchlanish', models.FloatField()),
                ('tok_kuchi', models.FloatField()),
                ('harorat', models.FloatField()),
                ('quvvat', models.FloatField()),
                ('chastota', models.FloatField()),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='station.station')),
            ],
        ),
        migrations.CreateModel(
            name='SunEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('kuchlanish', models.FloatField()),
                ('tok_kuchi', models.FloatField()),
                ('harorat', models.FloatField()),
                ('quvvat', models.FloatField()),
                ('chastota', models.FloatField()),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='station.station')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.region'),
        ),
        migrations.CreateModel(
            name='DiselEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('kuchlanish', models.FloatField()),
                ('tok_kuchi', models.FloatField()),
                ('harorat', models.FloatField()),
                ('quvvat', models.FloatField()),
                ('chastota', models.FloatField()),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='station.station')),
            ],
        ),
        migrations.CreateModel(
            name='AccumulatorEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('kuchlanish', models.FloatField()),
                ('tok_kuchi', models.FloatField()),
                ('harorat', models.FloatField()),
                ('quvvat', models.FloatField()),
                ('chastota', models.FloatField()),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='station.station')),
            ],
        ),
    ]
